# Generated by Django 5.1.7 on 2025-03-17 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0002_alter_artist_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artist',
            name='artist_name',
        ),
        migrations.AddField(
            model_name='artist',
            name='stage_name',
            field=models.CharField(null=True, unique=True, verbose_name='artist_name'),
        ),
    ]
