# Generated by Django 5.1.7 on 2025-03-18 04:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0003_remove_artist_artist_name_artist_stage_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='artist',
            old_name='number_of_albums_released',
            new_name='no_of_albums_released',
        ),
    ]
