# Generated by Django 5.1.7 on 2025-03-18 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0004_rename_number_of_albums_released_artist_no_of_albums_released'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='stage_name',
            field=models.CharField(null=True, unique=True, verbose_name='Stage Name'),
        ),
    ]
